import type { Metadata } from "next"
import { Nunito } from "next/font/google"
import "../globals.css";
import RootProvider from "@/components/providers/root-provider"
import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from "next-intl/server"

const nunito = Nunito({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-nunito',
});

export const metadata: Metadata = {
  title: {
    template: '%s | NextJs Template',
    default: 'NextJs Template',
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={`${nunito.className}`}>
        <NextIntlClientProvider
          messages={messages}
          locale={locale}>
          <RootProvider>
            {children}
          </RootProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
